# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
install:
  - R -e "0" --args --bootstrap-packrat
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
script:
  - chmod -R 755 .
  - ./deploy.sh
